-- ===========================================================================
-- CampusLens - PostgreSQL database schema (Supabase)
--
-- Applied by app/database.py -> init_db() only when DATABASE_URL is set.
-- Safe to re-run on every start: every statement uses IF NOT EXISTS, so
-- existing data is never dropped. The SQLite schema (schema.sql) remains the
-- local default and is unchanged.
--
-- Timestamps are TEXT in UTC produced by to_char(now() AT TIME ZONE 'utc',
-- 'YYYY-MM-DD HH24:MI:SS'), which renders exactly the same
-- 'YYYY-MM-DD HH:MM:SS' string as SQLite's datetime('now') - so the API and
-- the frontend see byte-identical values on both backends.
-- ===========================================================================

CREATE TABLE IF NOT EXISTS complaints (
    id                                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- What the student submitted -------------------------------------------
    description                          TEXT NOT NULL,
    location                             TEXT NOT NULL,
    image_path                           TEXT,          -- e.g. uploads/<uuid>.jpg

    -- Gemini's analysis ----------------------------------------------------
    category                             TEXT,
    issue_summary                        TEXT,
    safety_risk                          TEXT CHECK (safety_risk      IN ('Low', 'Medium', 'High')),
    functional_impact                    TEXT CHECK (functional_impact IN ('Low', 'Medium', 'High')),
    urgency                              TEXT CHECK (urgency          IN ('Low', 'Medium', 'High')),
    evidence_from_image                  TEXT,
    uncertainty_or_missing_information   TEXT,

    -- Priority (computed in Python, stored for sorting) ---------------------
    priority_score                       DOUBLE PRECISION, -- 0-100 (SQLite uses REAL)
    score_breakdown                      TEXT,          -- JSON string

    -- Workflow -------------------------------------------------------------
    status                               TEXT NOT NULL DEFAULT 'Reported'
                                         CHECK (status IN ('Reported', 'In Progress', 'Resolved')),

    -- Lifecycle timestamps (UTC, TEXT for exact SQLite-format parity) -------
    created_at                           TEXT NOT NULL
                                         DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
    updated_at                           TEXT,          -- set on status change
    resolved_at                          TEXT           -- set only when status becomes 'Resolved'
);

CREATE INDEX IF NOT EXISTS idx_complaints_status   ON complaints(status);
CREATE INDEX IF NOT EXISTS idx_complaints_category ON complaints(category);
CREATE INDEX IF NOT EXISTS idx_complaints_priority ON complaints(priority_score DESC);